# -*- coding: utf-8 -*-
"""Conjunto_datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T5LzFuncpMJaMZR4HGE6jtA7do6i--wV
"""

import pandas as pd
import numpy as np
import os
from google.colab import drive

# Montar Google Drive
drive.mount('/content/drive')

# Carpeta donde estarán todos los CSV individuales
ruta_base = '/content/drive/MyDrive/Proyecto_arroz/Conjunto_datos'

# Nombre del archivo final
ruta_salida = '/content/drive/MyDrive/Proyecto_arroz/dataset_grupo_final.csv'

# Cantidad esperada de columnas:
# 128 x 128 pixeles + 1 etiqueta final
columnas_esperadas = 128 * 128 + 1

datasets = []

print("--- Cargando y unificando archivos CSV ---")

# Buscar automáticamente todos los archivos .csv en la carpeta
archivos_csv = [
    archivo for archivo in os.listdir(ruta_base)
    if archivo.lower().endswith('.csv')
]

print(f"Archivos encontrados: {len(archivos_csv)}\n")

for archivo in archivos_csv:
    ruta_archivo = os.path.join(ruta_base, archivo)

    try:
        # Leer CSV intentando detectar separador automáticamente
        df = pd.read_csv(
            ruta_archivo,
            header=None,
            sep=None,
            engine='python'
        )

        # Si el archivo quedó en una sola columna, puede venir separado por ;
        if df.shape[1] == 1:
            df = df.iloc[:, 0].astype(str).str.split(';', expand=True)

        # Convertir todo a valores numéricos
        df = df.apply(pd.to_numeric, errors='coerce')

        # Eliminar filas que no sean numéricas
        # Esto elimina encabezados tipo pixel_0, pixel_1, ..., etiqueta_arroz
        df = df.dropna()

        # Convertir a enteros
        df = df.astype(int)

        # Validar cantidad de columnas
        if df.shape[1] != columnas_esperadas:
            print(f"Advertencia: {archivo} tiene {df.shape[1]} columnas, no {columnas_esperadas}. Se omitió.")
            continue

        # Asegurar que solo queden valores 0 y 1
        valores_unicos = np.unique(df.values)

        if not set(valores_unicos).issubset({0, 1}):
            print(f"Advertencia: {archivo} contiene valores distintos de 0 y 1: {valores_unicos}. Se omitió.")
            continue

        datasets.append(df)
        print(f"{archivo} cargado correctamente. Filas agregadas: {df.shape[0]}")

    except Exception as e:
        print(f"Error procesando {archivo}: {e}")

# Unificar y guardar dataset final
if datasets:
    dataset_final = pd.concat(datasets, ignore_index=True)

    # Guardar sin encabezado y sin índice
    dataset_final.to_csv(
        ruta_salida,
        index=False,
        header=False
    )

    print("\n" + "-" * 50)
    print("Dataset final creado correctamente.")
    print(f"Forma final del dataset: {dataset_final.shape}")
    print(f"Archivo guardado en: {ruta_salida}")

else:
    print("\nNo se pudo generar el dataset final. Revisa los archivos de entrada.")