# -*- coding: utf-8 -*-
"""Proyecto_arroz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M3ixhH6aLUe-jae9OjnA3fR8cg2_u5w
"""

import cv2
import numpy as np
import os
from google.colab import drive

# Montar Google Drive
drive.mount('/content/drive')

# Ruta base donde están las carpetas Positivo y Negativo
ruta_base = '/content/drive/MyDrive/Proyecto_arroz'

# Etiquetas:
# Positivo = imágenes con arroz
# Negativo = imágenes sin arroz, con otros objetos o vacías
carpetas = {
    'Positivo': 1,
    'Negativo': 0
}

# Tamaño requerido por el proyecto
ancho, alto = 128, 128

# Lista donde se guardarán todas las imágenes procesadas
matriz_final = []

print("Iniciando procesamiento desde Google Drive...")

for nombre_carpeta, etiqueta in carpetas.items():
    ruta_especifica = os.path.join(ruta_base, nombre_carpeta)

    if not os.path.exists(ruta_especifica):
        print(f"Error: No se encontró la carpeta en: {ruta_especifica}")
        continue

    # Se aceptan imágenes PNG, JPG y JPEG, incluso si la extensión está en mayúscula
    archivos = [
        f for f in os.listdir(ruta_especifica)
        if f.lower().endswith(('.png', '.jpg', '.jpeg'))
    ]

    print(f"Encontradas {len(archivos)} imágenes en '{nombre_carpeta}'")

    for nombre_archivo in archivos:
        path = os.path.join(ruta_especifica, nombre_archivo)

        # Leer imagen en escala de grises
        img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

        if img is not None:
            # Redimensionar a 128x128
            img_res = cv2.resize(img, (ancho, alto))

            # Binarización automática con Otsu
            # Resultado esperado:
            # fondo blanco = 255
            # objeto oscuro = 0
            _, seg = cv2.threshold(
                img_res,
                0,
                255,
                cv2.THRESH_BINARY + cv2.THRESH_OTSU
            )

            # Conversión a matriz de 1 y 0:
            # blanco/fondo = 1
            # objeto = 0
            img_binaria = (seg / 255).astype(np.uint8)

            # Convertir la imagen 128x128 en un vector fila de 16384 valores
            # y agregar la etiqueta al final
            vector_fila = np.append(img_binaria.flatten(), etiqueta)

            # Agregar la fila a la matriz final
            matriz_final.append(vector_fila)

        else:
            print(f"No se pudo leer la imagen: {path}")

# Guardar y exportar la matriz
if matriz_final:
    dataset = np.array(matriz_final, dtype=np.uint8)

    # Nombres de columnas
    columnas = [f'pixel_{i}' for i in range(128 * 128)] + ['etiqueta_arroz']
    encabezado = ",".join(columnas)

    # Rutas de salida
    nombre_salida_colab = "/content/matriz_final_drive.csv"
    nombre_salida_drive = "/content/drive/MyDrive/Proyecto_arroz/matriz_final.csv"

    # Guardar en Colab
    np.savetxt(
        nombre_salida_colab,
        dataset,
        delimiter=",",
        fmt='%d',
        header=encabezado,
        comments=''
    )

    # Guardar en Google Drive
    np.savetxt(
        nombre_salida_drive,
        dataset,
        delimiter=",",
        fmt='%d',
        header=encabezado,
        comments=''
    )

    print("-" * 40)
    print(f"¡Éxito! Matriz creada con forma: {dataset.shape}")
    print(f"Archivo guardado temporalmente en Colab como: {nombre_salida_colab}")
    print(f"Archivo guardado en Google Drive como: {nombre_salida_drive}")

else:
    print("No se procesó nada. Revisa si los nombres de las carpetas en Drive coinciden.")